### ISSUE TITLE
libteam.pc: useless "Requires: libnl-3.0"?

### ISSUE THREAD

**Issue by onlyjob** [jpirko/libteam#12]
It seems that `team.h` and `teamdctl.h` use no headers from `libnl-3-dev` so it might be that `Requires: libnl-3.0` in `libteam.pc` is unnecessary. See more in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=780855#10

**Comment by jpirko** [comment]
not sure how does that work in debian. But generally, libteam needs features which were added to libnl3.

**Comment by onlyjob** [comment]
OK, thanks for confirming. Perhaps on that instance no such features were used so linker gave a warning about "useless dependency"... Let's close this.

**Comment by rfc1036** [comment]
It works the same way on every Linux system: if libteam uses symbols from libnl-3 then libteam itself must be linked with libnl3.

Relying on the dynamic linker to find the symbols because the main binary is linked with libnl-3 works most of the time, but is broken.

FYI, the canonical reference about writing shared libraries is http://people.redhat.com/drepper/dsohowto.pdf  .
